### ISSUE TITLE
Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Notice: Uninitialized string offset: 0")

### ISSUE THREAD

**Issue by ibasaw** [carlos-granados/CgKintBundle#6]
When i do a  {{ kint() }} in my twig view, got this error

SF 2.8.9 on Sylius 0.18

is Kint use php eval code function ?

With a variable inside the kint call, got this one:

```
eval()'d code): failed to open stream: No such file or directory
```

**Comment by efalder413** [comment]
I also have this error. I'm running Symfony 3.1.5 with PHP 5.6.26 on AWS Linux 4.4.23-31.51.amzn1.x86_64

Screenshot of app_dev.php error page:
![image](https://cloud.githubusercontent.com/assets/6841035/19492172/79a76bf8-952a-11e6-8eee-d1250045d04e.png)

**Comment by ibasaw** [comment]
eval function is often used with malicious code, this is why some hosts, and me disabled it by default...

**Comment by efalder413** [comment]
I have not disabled eval unless it is disabled by default in Amazon's AWS Linux repos.
